services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "https://geo.mirror.pkgbuild.com/iso/2025.08.01/archlinux-2025.08.01-x86_64.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "512G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
